//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.237.
// 
#pragma warning disable 1591

namespace ClientBLL.UnoitServer {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UserService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateUserNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchEntryByNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchEntryByEntryIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchEntriesByKeywordsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SupportOperationCompleted;
        
        private System.Threading.SendOrPostCallback DisSupportOperationCompleted;
        
        private System.Threading.SendOrPostCallback EditEntryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserIdByNameOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserService() {
            this.Url = global::ClientBLL.Properties.Settings.Default.ClientBLL_UnoitServer_UserService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event ValidateUserNameCompletedEventHandler ValidateUserNameCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event SearchEntryByNameCompletedEventHandler SearchEntryByNameCompleted;
        
        /// <remarks/>
        public event SearchEntryByEntryIdCompletedEventHandler SearchEntryByEntryIdCompleted;
        
        /// <remarks/>
        public event SearchEntriesByKeywordsCompletedEventHandler SearchEntriesByKeywordsCompleted;
        
        /// <remarks/>
        public event SupportCompletedEventHandler SupportCompleted;
        
        /// <remarks/>
        public event DisSupportCompletedEventHandler DisSupportCompleted;
        
        /// <remarks/>
        public event EditEntryCompletedEventHandler EditEntryCompleted;
        
        /// <remarks/>
        public event GetUserIdByNameCompletedEventHandler GetUserIdByNameCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateUserName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidateUserName(string name) {
            object[] results = this.Invoke("ValidateUserName", new object[] {
                        name});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateUserNameAsync(string name) {
            this.ValidateUserNameAsync(name, null);
        }
        
        /// <remarks/>
        public void ValidateUserNameAsync(string name, object userState) {
            if ((this.ValidateUserNameOperationCompleted == null)) {
                this.ValidateUserNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateUserNameOperationCompleted);
            }
            this.InvokeAsync("ValidateUserName", new object[] {
                        name}, this.ValidateUserNameOperationCompleted, userState);
        }
        
        private void OnValidateUserNameOperationCompleted(object arg) {
            if ((this.ValidateUserNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateUserNameCompleted(this, new ValidateUserNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginStateFlag Login(string userName, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        userName,
                        password});
            return ((LoginStateFlag)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string password) {
            this.LoginAsync(userName, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string userName, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        userName,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchEntryByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Entry SearchEntryByName(string entryName) {
            object[] results = this.Invoke("SearchEntryByName", new object[] {
                        entryName});
            return ((Entry)(results[0]));
        }
        
        /// <remarks/>
        public void SearchEntryByNameAsync(string entryName) {
            this.SearchEntryByNameAsync(entryName, null);
        }
        
        /// <remarks/>
        public void SearchEntryByNameAsync(string entryName, object userState) {
            if ((this.SearchEntryByNameOperationCompleted == null)) {
                this.SearchEntryByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchEntryByNameOperationCompleted);
            }
            this.InvokeAsync("SearchEntryByName", new object[] {
                        entryName}, this.SearchEntryByNameOperationCompleted, userState);
        }
        
        private void OnSearchEntryByNameOperationCompleted(object arg) {
            if ((this.SearchEntryByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchEntryByNameCompleted(this, new SearchEntryByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchEntryByEntryId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Entry SearchEntryByEntryId(int entryId) {
            object[] results = this.Invoke("SearchEntryByEntryId", new object[] {
                        entryId});
            return ((Entry)(results[0]));
        }
        
        /// <remarks/>
        public void SearchEntryByEntryIdAsync(int entryId) {
            this.SearchEntryByEntryIdAsync(entryId, null);
        }
        
        /// <remarks/>
        public void SearchEntryByEntryIdAsync(int entryId, object userState) {
            if ((this.SearchEntryByEntryIdOperationCompleted == null)) {
                this.SearchEntryByEntryIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchEntryByEntryIdOperationCompleted);
            }
            this.InvokeAsync("SearchEntryByEntryId", new object[] {
                        entryId}, this.SearchEntryByEntryIdOperationCompleted, userState);
        }
        
        private void OnSearchEntryByEntryIdOperationCompleted(object arg) {
            if ((this.SearchEntryByEntryIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchEntryByEntryIdCompleted(this, new SearchEntryByEntryIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SearchEntriesByKeywords", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Entry[] SearchEntriesByKeywords(string keyword) {
            object[] results = this.Invoke("SearchEntriesByKeywords", new object[] {
                        keyword});
            return ((Entry[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchEntriesByKeywordsAsync(string keyword) {
            this.SearchEntriesByKeywordsAsync(keyword, null);
        }
        
        /// <remarks/>
        public void SearchEntriesByKeywordsAsync(string keyword, object userState) {
            if ((this.SearchEntriesByKeywordsOperationCompleted == null)) {
                this.SearchEntriesByKeywordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchEntriesByKeywordsOperationCompleted);
            }
            this.InvokeAsync("SearchEntriesByKeywords", new object[] {
                        keyword}, this.SearchEntriesByKeywordsOperationCompleted, userState);
        }
        
        private void OnSearchEntriesByKeywordsOperationCompleted(object arg) {
            if ((this.SearchEntriesByKeywordsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchEntriesByKeywordsCompleted(this, new SearchEntriesByKeywordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Support", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Support(string entryName, string userName) {
            object[] results = this.Invoke("Support", new object[] {
                        entryName,
                        userName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SupportAsync(string entryName, string userName) {
            this.SupportAsync(entryName, userName, null);
        }
        
        /// <remarks/>
        public void SupportAsync(string entryName, string userName, object userState) {
            if ((this.SupportOperationCompleted == null)) {
                this.SupportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSupportOperationCompleted);
            }
            this.InvokeAsync("Support", new object[] {
                        entryName,
                        userName}, this.SupportOperationCompleted, userState);
        }
        
        private void OnSupportOperationCompleted(object arg) {
            if ((this.SupportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SupportCompleted(this, new SupportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DisSupport", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DisSupport(string entryName, string userName) {
            object[] results = this.Invoke("DisSupport", new object[] {
                        entryName,
                        userName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DisSupportAsync(string entryName, string userName) {
            this.DisSupportAsync(entryName, userName, null);
        }
        
        /// <remarks/>
        public void DisSupportAsync(string entryName, string userName, object userState) {
            if ((this.DisSupportOperationCompleted == null)) {
                this.DisSupportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDisSupportOperationCompleted);
            }
            this.InvokeAsync("DisSupport", new object[] {
                        entryName,
                        userName}, this.DisSupportOperationCompleted, userState);
        }
        
        private void OnDisSupportOperationCompleted(object arg) {
            if ((this.DisSupportCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DisSupportCompleted(this, new DisSupportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EditEntry", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EditEntry(EntryToBeVerified newEntry) {
            object[] results = this.Invoke("EditEntry", new object[] {
                        newEntry});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EditEntryAsync(EntryToBeVerified newEntry) {
            this.EditEntryAsync(newEntry, null);
        }
        
        /// <remarks/>
        public void EditEntryAsync(EntryToBeVerified newEntry, object userState) {
            if ((this.EditEntryOperationCompleted == null)) {
                this.EditEntryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEditEntryOperationCompleted);
            }
            this.InvokeAsync("EditEntry", new object[] {
                        newEntry}, this.EditEntryOperationCompleted, userState);
        }
        
        private void OnEditEntryOperationCompleted(object arg) {
            if ((this.EditEntryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EditEntryCompleted(this, new EditEntryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserIdByName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetUserIdByName(string userName) {
            object[] results = this.Invoke("GetUserIdByName", new object[] {
                        userName});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserIdByNameAsync(string userName) {
            this.GetUserIdByNameAsync(userName, null);
        }
        
        /// <remarks/>
        public void GetUserIdByNameAsync(string userName, object userState) {
            if ((this.GetUserIdByNameOperationCompleted == null)) {
                this.GetUserIdByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserIdByNameOperationCompleted);
            }
            this.InvokeAsync("GetUserIdByName", new object[] {
                        userName}, this.GetUserIdByNameOperationCompleted, userState);
        }
        
        private void OnGetUserIdByNameOperationCompleted(object arg) {
            if ((this.GetUserIdByNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserIdByNameCompleted(this, new GetUserIdByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LoginStateFlag {
        
        /// <remarks/>
        USERSUCCESS,
        
        /// <remarks/>
        ADMINSUCCESS,
        
        /// <remarks/>
        PASSWORDERROR,
        
        /// <remarks/>
        USERNAMENOTEXIST,
        
        /// <remarks/>
        NONACTIVATED,
        
        /// <remarks/>
        ACCOUNTFREEZE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Entry : EntryToBeVerified {
        
        private string[] keywordsField;
        
        private int clickSumField;
        
        private System.DateTime lastModificationField;
        
        private int digSumField;
        
        private int upSumField;
        
        /// <remarks/>
        public string[] Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        public int ClickSum {
            get {
                return this.clickSumField;
            }
            set {
                this.clickSumField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastModification {
            get {
                return this.lastModificationField;
            }
            set {
                this.lastModificationField = value;
            }
        }
        
        /// <remarks/>
        public int DigSum {
            get {
                return this.digSumField;
            }
            set {
                this.digSumField = value;
            }
        }
        
        /// <remarks/>
        public int UpSum {
            get {
                return this.upSumField;
            }
            set {
                this.upSumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Entry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntryToBeVerified {
        
        private int catagoryIdField;
        
        private string entryNameField;
        
        private string contentField;
        
        private int userIdField;
        
        private string sourceField;
        
        private System.DateTime releasedTimeField;
        
        private int entryIdField;
        
        /// <remarks/>
        public int CatagoryId {
            get {
                return this.catagoryIdField;
            }
            set {
                this.catagoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string EntryName {
            get {
                return this.entryNameField;
            }
            set {
                this.entryNameField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ReleasedTime {
            get {
                return this.releasedTimeField;
            }
            set {
                this.releasedTimeField = value;
            }
        }
        
        /// <remarks/>
        public int EntryId {
            get {
                return this.entryIdField;
            }
            set {
                this.entryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ValidateUserNameCompletedEventHandler(object sender, ValidateUserNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateUserNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateUserNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginStateFlag Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginStateFlag)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchEntryByNameCompletedEventHandler(object sender, SearchEntryByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchEntryByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchEntryByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Entry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Entry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchEntryByEntryIdCompletedEventHandler(object sender, SearchEntryByEntryIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchEntryByEntryIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchEntryByEntryIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Entry Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Entry)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SearchEntriesByKeywordsCompletedEventHandler(object sender, SearchEntriesByKeywordsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchEntriesByKeywordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchEntriesByKeywordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Entry[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Entry[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SupportCompletedEventHandler(object sender, SupportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DisSupportCompletedEventHandler(object sender, DisSupportCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DisSupportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DisSupportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EditEntryCompletedEventHandler(object sender, EditEntryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EditEntryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EditEntryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetUserIdByNameCompletedEventHandler(object sender, GetUserIdByNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserIdByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserIdByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591